-- AUTO-GENERATED from lib/content/seed.ts — do not edit by hand.
-- Regenerate: node --experimental-strip-types scripts/gen-seed-sql.mjs

insert into profile (id, full_name, name, title, tagline, location, email, phone, availability, availability_note, summary, about, socials, resume_url, avatar_url)
values ('me', 'Ishan Bhaveshbhai Savaliya', 'Ishan Savaliya', 'Full-Stack Developer', 'Building production-grade web apps across React.js & Spring Boot ecosystems.', 'Surat, Gujarat, India', 'ishansavaliya787@gmail.com', '+91 7990408235', 'open', 'Open to full-time & freelance opportunities', 'Full-Stack Developer with hands-on experience building production-grade web applications across React.js and Spring Boot ecosystems. Skilled in designing scalable backend systems, REST APIs, and schema-driven architectures with PostgreSQL and dynamic data models. Experienced in cloud deployment, CI/CD pipelines, and distributed system workflows using AWS, DigitalOcean, and modern DevOps tools. Focused on delivering high-performance applications with clean system design, real-world problem solving, and AI-integrated features.', '["I''m a Full-Stack Developer currently building production systems at EMGAGE, working across React.js, Spring Boot, Hibernate and SQL with scalable architecture design.","I love designing schema-driven backends, REST APIs and AI-integrated features — and shipping them to the cloud with CI/CD pipelines on AWS and DigitalOcean.","When I''m not coding, I''m sharpening DSA, exploring system design, and building side projects that solve real problems.","I also have a strong interest in Data Science, Machine Learning and AI agents."]'::jsonb, '[{"label":"GitHub","url":"https://github.com/ishansavaliya","handle":"ishansavaliya"},{"label":"LinkedIn","url":"https://linkedin.com/in/iamishansavaliya","handle":"iamishansavaliya"},{"label":"LeetCode","url":"https://leetcode.com/u/ishansavaliya","handle":"ishansavaliya"},{"label":"Codolio","url":"https://codolio.com/profile/ishansavaliya","handle":"ishansavaliya"},{"label":"Portfolio","url":"https://ishansavaliya.vercel.app","handle":"ishansavaliya.vercel.app"}]'::jsonb, '/resume/ishan-savaliya-resume.pdf', '/brand/is-logo.png')
on conflict (id) do update set full_name=excluded.full_name, name=excluded.name, title=excluded.title, tagline=excluded.tagline, location=excluded.location, email=excluded.email, phone=excluded.phone, availability=excluded.availability, availability_note=excluded.availability_note, summary=excluded.summary, about=excluded.about, socials=excluded.socials, resume_url=excluded.resume_url, avatar_url=excluded.avatar_url;

insert into experience (id, company, role, type, start_label, end_label, location, current, highlights, stack, sort_order)
values ('emgage', 'EMGAGE', 'Full-Stack Developer Intern', 'internship', 'Sept 2025', 'Present', 'India', true, '["Working on production-grade full-stack applications using React.js, Spring Boot, Hibernate, and SQL with scalable architecture design.","Designed and developed RESTful APIs and integrated them with dynamic front-end systems ensuring high performance and responsiveness.","Implemented CI/CD pipelines using Jenkins for automated build, testing, and deployment workflows.","Deployed applications on AWS cloud infrastructure including EC2, S3, and cloud-based environments for scalability and reliability.","Managed GitLab repositories with complete branch management workflows including feature branching, merging, and version control.","Collaborated in agile development cycles — sprint planning, code reviews, and production releases.","Worked on AI-based integrations including MCP architecture and intelligent system enhancements in real-world applications.","Improved application performance, optimized backend queries, and enhanced system reliability for production-level systems."]'::jsonb, '["React.js","Spring Boot","Hibernate","SQL","Jenkins","AWS","GitLab","MCP"]'::jsonb, 0)
on conflict (id) do update set company=excluded.company, role=excluded.role, type=excluded.type, start_label=excluded.start_label, end_label=excluded.end_label, location=excluded.location, current=excluded.current, highlights=excluded.highlights, stack=excluded.stack, sort_order=excluded.sort_order;
insert into experience (id, company, role, type, start_label, end_label, location, current, highlights, stack, sort_order)
values ('brainybeam', 'Brainybeam Info-Tech Pvt. Ltd.', 'MERN Stack Intern', 'internship', 'May 2025', 'June 2025', 'India', false, '["Contributed to live MERN stack projects and collaborated with senior developers in a fast-paced agile environment.","Gained hands-on experience in full-stack development, enhancing skills in MongoDB, Express.js, React.js, and Node.js.","Improved code quality, debugging techniques, and deployment workflows through real-world development tasks."]'::jsonb, '["MongoDB","Express.js","React.js","Node.js"]'::jsonb, 1)
on conflict (id) do update set company=excluded.company, role=excluded.role, type=excluded.type, start_label=excluded.start_label, end_label=excluded.end_label, location=excluded.location, current=excluded.current, highlights=excluded.highlights, stack=excluded.stack, sort_order=excluded.sort_order;
insert into experience (id, company, role, type, start_label, end_label, location, current, highlights, stack, sort_order)
values ('greendotslab', 'Greendotslab Software Solutions', 'Junior Developer (Internship)', 'internship', '2025', '2025', 'Surat, Gujarat', false, '["Recognized by the proprietor for strong skills, work ethic and character during the internship.","Recommended for Junior Developer roles — “a quick learner with a positive mindset, a pleasure to work with.”"]'::jsonb, '["JavaScript","React.js","Node.js"]'::jsonb, 2)
on conflict (id) do update set company=excluded.company, role=excluded.role, type=excluded.type, start_label=excluded.start_label, end_label=excluded.end_label, location=excluded.location, current=excluded.current, highlights=excluded.highlights, stack=excluded.stack, sort_order=excluded.sort_order;

insert into projects (id, name, tagline, category, featured, description, highlights, stack, github, live, metrics, sort_order)
values ('interviewready', 'InterviewReady', 'AI Interview Platform', 'personal', true, 'An AI-driven web app simulating real interviews with speech-to-text, webcam feedback, and analytics.', '["Developed an AI-driven web app simulating real interviews with speech-to-text, webcam feedback, and analytics.","Boosted candidate preparation efficiency by 50% through personalized resume tools and real-time coaching.","Integrated resume builder, career chatbot, and performance analysis dashboards for improved user engagement."]'::jsonb, '["React.js","Tailwind CSS","TypeScript","Firebase","Gemini API"]'::jsonb, 'https://github.com/ishansavaliya/InterviewReady-an-AI-Interview-Preparation', null, '[{"label":"Prep efficiency","value":"+50%"}]'::jsonb, 0)
on conflict (id) do update set name=excluded.name, tagline=excluded.tagline, category=excluded.category, featured=excluded.featured, description=excluded.description, highlights=excluded.highlights, stack=excluded.stack, github=excluded.github, live=excluded.live, metrics=excluded.metrics, sort_order=excluded.sort_order;
insert into projects (id, name, tagline, category, featured, description, highlights, stack, github, live, metrics, sort_order)
values ('wire2web', 'Wire2Web', 'AI Wireframe to Code Converter', 'personal', true, 'A responsive platform converting wireframes into code using AI models like OpenAI, Gemini, and Llama, with real-time code generation and export.', '["Built a responsive React + Tailwind platform converting wireframes using AI models like OpenAI, Gemini, and Llama, enabling real-time code and export features.","Increased developer productivity by 35% and reduced front-end effort by 40% with design management and code regeneration."]'::jsonb, '["Next.js 15","React 18","Tailwind CSS","Firebase","Drizzle ORM"]'::jsonb, 'https://github.com/ishansavaliya/Wire2Web-Wireframe-to-Code-Generator', null, '[{"label":"Productivity","value":"+35%"},{"label":"FE effort","value":"-40%"}]'::jsonb, 1)
on conflict (id) do update set name=excluded.name, tagline=excluded.tagline, category=excluded.category, featured=excluded.featured, description=excluded.description, highlights=excluded.highlights, stack=excluded.stack, github=excluded.github, live=excluded.live, metrics=excluded.metrics, sort_order=excluded.sort_order;
insert into projects (id, name, tagline, category, featured, description, highlights, stack, github, live, metrics, sort_order)
values ('jobverse', 'JobVerse', 'Full-Stack Job Portal', 'personal', true, 'A full-stack job portal connecting recruiters and job seekers with secure JWT auth, dashboards and recruiter workflows.', '["Developed a full-stack job portal connecting recruiters and job seekers with secure JWT authentication, dashboards, Redux, RESTful APIs, Cloudinary, and responsive routing.","Reduced hiring time by 30% by streamlining applications, job posts, and recruiter workflows."]'::jsonb, '["React.js","Node.js","MongoDB","Express.js","JWT","Redux"]'::jsonb, 'https://github.com/ishansavaliya/JobVerse-a-Job-Portal-Website', null, '[{"label":"Hiring time","value":"-30%"}]'::jsonb, 2)
on conflict (id) do update set name=excluded.name, tagline=excluded.tagline, category=excluded.category, featured=excluded.featured, description=excluded.description, highlights=excluded.highlights, stack=excluded.stack, github=excluded.github, live=excluded.live, metrics=excluded.metrics, sort_order=excluded.sort_order;
insert into projects (id, name, tagline, category, featured, description, highlights, stack, github, live, metrics, sort_order)
values ('farmzy', 'Farmzy', 'Multi-Vendor Event & Service Booking System', 'freelance', true, 'A multi-vendor booking system for event services (venues, photography, DJ) with schema-driven architecture and multi-service bookings in a single flow.', '["Developed a multi-vendor booking system enabling users to discover and book event services with support for multi-service bookings in a single flow.","Implemented a schema-driven architecture where dynamic forms, filters, and listing structures are generated from backend-defined JSON schemas.","Designed a modular backend using Spring Boot with REST APIs for services, bookings, categories, and vendor workflows.","Built a PostgreSQL data model using JSONB fields to store dynamic attributes, eliminating rigid schema constraints across service categories.","Implemented booking system with parent-child structure (bookings + booking_items) to support multi-vendor transactions.","Developed role-based workflows including vendor listing submission, admin approval pipeline (Draft → Pending → Approved), and user booking lifecycle.","Integrated availability management using date-based blocking and validation before booking confirmation."]'::jsonb, '["React","Spring Boot","PostgreSQL (JSONB)","Redis","Elasticsearch","DigitalOcean","Cloudflare","Vercel"]'::jsonb, null, 'https://www.farmzy.studio', '[]'::jsonb, 3)
on conflict (id) do update set name=excluded.name, tagline=excluded.tagline, category=excluded.category, featured=excluded.featured, description=excluded.description, highlights=excluded.highlights, stack=excluded.stack, github=excluded.github, live=excluded.live, metrics=excluded.metrics, sort_order=excluded.sort_order;
insert into projects (id, name, tagline, category, featured, description, highlights, stack, github, live, metrics, sort_order)
values ('firefighter', 'FireFighter E-Commerce', 'Multi-Role E-Commerce Platform', 'freelance', false, 'A complete multi-role e-commerce system for firefighters with Admin, Vendor, and User panels and Razorpay payments.', '["Developed a complete multi-role e-commerce system for firefighters including Admin, Vendor, and User panels.","Built secure authentication, product management, order workflows, and role-based dashboards.","Integrated Razorpay payment gateway for seamless online transactions.","Designed scalable backend APIs and responsive UI for real-world client usage."]'::jsonb, '["MongoDB","Express.js","React.js","Node.js","Razorpay"]'::jsonb, null, null, '[]'::jsonb, 4)
on conflict (id) do update set name=excluded.name, tagline=excluded.tagline, category=excluded.category, featured=excluded.featured, description=excluded.description, highlights=excluded.highlights, stack=excluded.stack, github=excluded.github, live=excluded.live, metrics=excluded.metrics, sort_order=excluded.sort_order;
insert into projects (id, name, tagline, category, featured, description, highlights, stack, github, live, metrics, sort_order)
values ('catering-cms', 'Catering Business Website', 'Next.js + Sanity CMS', 'freelance', false, 'A modern, SEO-optimized static website with SSR and a Sanity CMS for client-managed content.', '["Built a modern, SEO-optimized static website using Next.js with server-side rendering and optimized performance.","Integrated Sanity CMS for dynamic blog and content management enabling client-side updates without developer dependency.","Configured domain and deployment using Hostinger with production-ready setup and performance tuning."]'::jsonb, '["Next.js","Sanity CMS","JavaScript","Hostinger"]'::jsonb, null, null, '[]'::jsonb, 5)
on conflict (id) do update set name=excluded.name, tagline=excluded.tagline, category=excluded.category, featured=excluded.featured, description=excluded.description, highlights=excluded.highlights, stack=excluded.stack, github=excluded.github, live=excluded.live, metrics=excluded.metrics, sort_order=excluded.sort_order;
insert into projects (id, name, tagline, category, featured, description, highlights, stack, github, live, metrics, sort_order)
values ('agripredict', 'Crop Recommendation System', 'ML Agriculture Platform', 'data-science', false, 'A Machine Learning system using Random Forest to analyze soil parameters and recommend optimal crops with 93.86% accuracy.', '["Developed a Machine Learning system using Random Forest Classifier to analyze soil parameters and recommend optimal crops with 93.86% accuracy.","Increased crop yield predictions by 25% and improved resource efficiency for farmers through data-driven agricultural insights."]'::jsonb, '["Python","Random Forest","Streamlit","Scikit-learn","Pandas","NumPy"]'::jsonb, 'https://github.com/ishansavaliya/AgriPredict', null, '[{"label":"Accuracy","value":"93.86%"}]'::jsonb, 6)
on conflict (id) do update set name=excluded.name, tagline=excluded.tagline, category=excluded.category, featured=excluded.featured, description=excluded.description, highlights=excluded.highlights, stack=excluded.stack, github=excluded.github, live=excluded.live, metrics=excluded.metrics, sort_order=excluded.sort_order;
insert into projects (id, name, tagline, category, featured, description, highlights, stack, github, live, metrics, sort_order)
values ('heart-disease', 'Heart Disease Prediction', 'Medical AI Platform', 'data-science', false, 'A healthcare prediction system using Logistic Regression to assess heart disease risk from medical parameters.', '["Built a healthcare prediction system using Logistic Regression to analyze medical parameters and predict heart disease risk with high accuracy.","Reduced diagnostic delays by 40% by providing quick risk assessment for healthcare professionals and individuals."]'::jsonb, '["Python","Logistic Regression","Streamlit","Pandas","NumPy","Scikit-learn"]'::jsonb, 'https://github.com/ishansavaliya/Heart-Disease-Prediction', null, '[]'::jsonb, 7)
on conflict (id) do update set name=excluded.name, tagline=excluded.tagline, category=excluded.category, featured=excluded.featured, description=excluded.description, highlights=excluded.highlights, stack=excluded.stack, github=excluded.github, live=excluded.live, metrics=excluded.metrics, sort_order=excluded.sort_order;
insert into projects (id, name, tagline, category, featured, description, highlights, stack, github, live, metrics, sort_order)
values ('stock-market', 'Stock Market Prediction', 'Finance Forecasting Platform', 'data-science', false, 'A stock forecasting system using statistical and ML techniques with an interactive search-and-visualize web interface.', '["Developed a stock market forecasting system using statistical and machine learning techniques to analyze historical stock data and predict future trends.","Created an interactive web interface allowing users to search companies and visualize stock predictions with dynamic charts."]'::jsonb, '["Python","Streamlit","YFinance","Scikit-learn","Pandas"]'::jsonb, 'https://github.com/ishansavaliya/Stock-Market-Prediction', null, '[]'::jsonb, 8)
on conflict (id) do update set name=excluded.name, tagline=excluded.tagline, category=excluded.category, featured=excluded.featured, description=excluded.description, highlights=excluded.highlights, stack=excluded.stack, github=excluded.github, live=excluded.live, metrics=excluded.metrics, sort_order=excluded.sort_order;

insert into skills (id, label, skills, sort_order)
values ('frontend', 'Frontend', '[{"name":"React.js","level":"advanced"},{"name":"Next.js","level":"advanced"},{"name":"TypeScript","level":"advanced"},{"name":"JavaScript","level":"expert"},{"name":"Tailwind CSS","level":"advanced"},{"name":"HTML","level":"expert"},{"name":"CSS","level":"expert"}]'::jsonb, 0)
on conflict (id) do update set label=excluded.label, skills=excluded.skills, sort_order=excluded.sort_order;
insert into skills (id, label, skills, sort_order)
values ('backend', 'Backend', '[{"name":"Spring Boot","level":"advanced"},{"name":"Node.js","level":"advanced"},{"name":"Express.js","level":"advanced"},{"name":"Hibernate","level":"intermediate"},{"name":"RESTful API","level":"advanced"},{"name":"Firebase","level":"intermediate"}]'::jsonb, 1)
on conflict (id) do update set label=excluded.label, skills=excluded.skills, sort_order=excluded.sort_order;
insert into skills (id, label, skills, sort_order)
values ('databases', 'Databases', '[{"name":"PostgreSQL (JSONB)","level":"advanced"},{"name":"MongoDB","level":"advanced"},{"name":"SQL","level":"advanced"},{"name":"Redis","level":"intermediate"},{"name":"Elasticsearch","level":"intermediate"}]'::jsonb, 2)
on conflict (id) do update set label=excluded.label, skills=excluded.skills, sort_order=excluded.sort_order;
insert into skills (id, label, skills, sort_order)
values ('languages', 'Languages', '[{"name":"JavaScript","level":"expert"},{"name":"TypeScript","level":"advanced"},{"name":"Java","level":"advanced"},{"name":"Python","level":"advanced"}]'::jsonb, 3)
on conflict (id) do update set label=excluded.label, skills=excluded.skills, sort_order=excluded.sort_order;
insert into skills (id, label, skills, sort_order)
values ('devops', 'Tools & DevOps', '[{"name":"Git","level":"expert"},{"name":"GitHub","level":"expert"},{"name":"GitLab","level":"advanced"},{"name":"Docker","level":"advanced"},{"name":"Jenkins","level":"intermediate"},{"name":"AWS","level":"intermediate"},{"name":"DigitalOcean","level":"intermediate"},{"name":"Cloudflare","level":"intermediate"},{"name":"Linux","level":"advanced"},{"name":"Bash","level":"advanced"},{"name":"Vercel","level":"advanced"}]'::jsonb, 4)
on conflict (id) do update set label=excluded.label, skills=excluded.skills, sort_order=excluded.sort_order;
insert into skills (id, label, skills, sort_order)
values ('ml', 'ML & Data', '[{"name":"Scikit-learn","level":"intermediate"},{"name":"Pandas","level":"intermediate"},{"name":"NumPy","level":"intermediate"},{"name":"Streamlit","level":"intermediate"}]'::jsonb, 5)
on conflict (id) do update set label=excluded.label, skills=excluded.skills, sort_order=excluded.sort_order;
insert into skills (id, label, skills, sort_order)
values ('other', 'Other', '[{"name":"Data Structures & Algorithms","level":"advanced"},{"name":"System Design Basics","level":"intermediate"},{"name":"API Design","level":"advanced"},{"name":"CI/CD Pipelines","level":"advanced"}]'::jsonb, 6)
on conflict (id) do update set label=excluded.label, skills=excluded.skills, sort_order=excluded.sort_order;

insert into education (id, institution, degree, grade, start_label, end_label, location, sort_order)
values ('adit', 'A.D. Patel Institute of Technology', 'B.Tech in Information Technology', 'CGPA: 8.49', '2022', '2026', 'Anand, Gujarat', 0)
on conflict (id) do update set institution=excluded.institution, degree=excluded.degree, grade=excluded.grade, start_label=excluded.start_label, end_label=excluded.end_label, location=excluded.location, sort_order=excluded.sort_order;
insert into education (id, institution, degree, grade, start_label, end_label, location, sort_order)
values ('hsc', 'Nalanda Vidhyalaya - 2', 'HSC (Higher Secondary)', 'Grade A2 · Percentile 97.04', '', '2022', 'Surat, Gujarat', 1)
on conflict (id) do update set institution=excluded.institution, degree=excluded.degree, grade=excluded.grade, start_label=excluded.start_label, end_label=excluded.end_label, location=excluded.location, sort_order=excluded.sort_order;
insert into education (id, institution, degree, grade, start_label, end_label, location, sort_order)
values ('ssc', 'Nalanda Vidhyalaya - 2', 'SSC (Secondary)', 'Grade A2 · Percentile 98.43', '', '2020', 'Surat, Gujarat', 2)
on conflict (id) do update set institution=excluded.institution, degree=excluded.degree, grade=excluded.grade, start_label=excluded.start_label, end_label=excluded.end_label, location=excluded.location, sort_order=excluded.sort_order;

insert into certifications (id, name, issuer, url, category, sort_order)
values ('meta-frontend', 'Meta Front-End Developer', 'Meta · Coursera', 'https://www.coursera.org/account/accomplishments/specialization/5GDQX7IDJ8O0', 'Meta', 0)
on conflict (id) do update set name=excluded.name, issuer=excluded.issuer, url=excluded.url, category=excluded.category, sort_order=excluded.sort_order;
insert into certifications (id, name, issuer, url, category, sort_order)
values ('meta-backend', 'Meta Back-End Developer', 'Meta · Coursera', 'https://www.coursera.org/account/accomplishments/specialization/O4QYH20S8AAM', 'Meta', 1)
on conflict (id) do update set name=excluded.name, issuer=excluded.issuer, url=excluded.url, category=excluded.category, sort_order=excluded.sort_order;
insert into certifications (id, name, issuer, url, category, sort_order)
values ('ibm-ds', 'IBM Data Science Professional Certificate', 'IBM · Coursera', 'https://www.coursera.org/account/accomplishments/specialization/1SMHP7J5TO89', 'IBM', 2)
on conflict (id) do update set name=excluded.name, issuer=excluded.issuer, url=excluded.url, category=excluded.category, sort_order=excluded.sort_order;

insert into testimonials (id, name, role, company, quote, url, approved)
values ('nikunj-greendotslab', 'Nikunj Sardhara', 'Proprietor', 'Greendotslab Software Solutions', 'It is my pleasure to recommend Ishan Savaliya. During his internship I was consistently impressed by his skills, work ethic and character. He is a quick learner with a positive mindset — a pleasure to work with.', null, true)
on conflict (id) do update set name=excluded.name, role=excluded.role, company=excluded.company, quote=excluded.quote, url=excluded.url, approved=excluded.approved;

insert into achievements (id, title, description, date_label, category, sort_order)
values ('emgage-prod', 'Shipping production systems at EMGAGE', 'Building and deploying production-grade full-stack applications with CI/CD on AWS.', '2025', 'milestone', 0)
on conflict (id) do update set title=excluded.title, description=excluded.description, date_label=excluded.date_label, category=excluded.category, sort_order=excluded.sort_order;
insert into achievements (id, title, description, date_label, category, sort_order)
values ('farmzy-live', 'Farmzy live for a real client', 'Delivered a schema-driven multi-vendor booking platform now live at farmzy.studio.', null, 'milestone', 1)
on conflict (id) do update set title=excluded.title, description=excluded.description, date_label=excluded.date_label, category=excluded.category, sort_order=excluded.sort_order;
insert into achievements (id, title, description, date_label, category, sort_order)
values ('agri-accuracy', '93.86% ML model accuracy', 'Crop Recommendation System using Random Forest reached 93.86% classification accuracy.', null, 'milestone', 2)
on conflict (id) do update set title=excluded.title, description=excluded.description, date_label=excluded.date_label, category=excluded.category, sort_order=excluded.sort_order;
